### ISSUE TITLE
[Pi5] Lock-ups

### ISSUE THREAD

**Issue by procount** [procount/pinn#770]
Model: Pi5 
PINN: v3.8.9
Occasionally and randomly, PINN will freeze, requiring a reboot.
This seems to happen just after the wifi has established and the IP address has been set.

**Comment by Poopi** [comment]
100% reproducible when moving the USB mouse

**Comment by procount** [comment]
Yes I had suspected something similar myself.

**Comment by Poopi** [comment]
Do you have a beta branch somewhere to look at?

**Comment by Poopi** [comment]
Was thinking about source code rather that binaries that I already checked...

**Comment by procount** [comment]
I need to get it into a fit state first, then I'll consider pushing it up.
The odd thing is that apart from the removal of the alternate bootloading mechanism, the PINN source code is virtually the same as before. The 6.1 kernel is the same across all the models, but only the 64-bit version for the Pi5 exhibits this issue.
I think it's more of a kernel issue, unless it's the kernel that's highlighting a latent problem in the application 🤷‍♂️

**Comment by Poopi** [comment]
I do think it is the latter. I do have an old Xiaomi keyboard that generates spurious messages in kernel. When PINN hangs I can simply remove the dongle and the boot continues....

**Comment by procount** [comment]
When it locks up, it seems to be stuck here:
```
(gdb) backtrace
#0  0xf6cc81c8 in pthread_cond_wait () from /home/pi5/buildroot/output/host/usr/arm-buildroot-linux-uclibcgnueabi/sysroot/lib/libpthread.so.0
#1  0x015f9750 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) bt
#0  0xf6cc81c8 in pthread_cond_wait () from /home/pi5/buildroot/output/host/usr/arm-buildroot-linux-uclibcgnueabi/sysroot/lib/libpthread.so.0
#1  0x015f9750 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```
So, probably a thread or stack error.....?
